// NMEA 2000 Manufacturers, Classes, Functions, and PGN descriptions

export const MANUFACTURERS: Record<number, string> = {
  78: 'Fw Murphy',
  80: 'Twin Disc',
  85: 'Kohler Power Systems',
  88: 'Hemisphere',
  116: 'BEP Marine',
  135: 'Airmar',
  137: 'Maretron',
  140: 'Lowrance',
  144: 'Mercury Marine',
  147: 'Nautibus Electronic Gmbh',
  148: 'Blue Water Data',
  154: 'Westerbeke',
  161: 'Offshore Systems UK',
  163: 'Evinrude/Brp Bombardier',
  165: 'CPAC Systems Ab',
  168: 'Xantrex Technology',
  172: 'Yanmar Marine',
  174: 'Ab Volvo/Volvo Penta',
  176: 'Carling Technologies',
  185: 'Beede Electrical',
  192: 'Floscan Instrument Co., Inc.',
  193: 'Nobeltec',
  198: 'Mystic Valley Communications',
  199: 'Actia Corporation',
  201: 'Disenos Y Technologia',
  211: 'Digital Switching Systems',
  215: 'Xintex/Atena',
  224: 'Emmi Network',
  228: 'Zf Marine Electronics',
  229: 'Garmin',
  233: 'Yacht Monitoring Solutions',
  235: 'Sailormade Marine Telemetry',
  243: 'Eride',
  257: 'Honda Motor Company',
  272: 'Groco',
  273: 'Actisense',
  274: 'Amphenol Ltw Technology',
  275: 'Navico',
  283: 'Hamilton Jet',
  285: 'Sea Recovery',
  286: 'Coelmo Srl Italy',
  295: 'BEP Marine',
  299: 'Garmin',
  304: 'Trigentic/EmpirBus',
  305: 'Novatel',
  306: 'Sleipner Motor As',
  307: 'Mbw Technologies',
  315: 'ICOM',
  328: 'Qwerty',
  329: 'Dief',
  341: 'Böning Automationstechnologie GmbH',
  345: 'Korea Maritime University',
  351: 'Thrane And Thrane',
  355: 'Mastervolt',
  356: 'Fischer Panda Generators',
  358: 'Victron Energy',
  370: 'Rolls Royce Marine',
  373: 'Electronic Design',
  374: 'Northern Lights',
  378: 'Glendinning',
  381: 'B&G',
  384: 'Rose Point Navigation Systems',
  385: 'Johnson Outdoors Marine Electronics',
  394: 'Capi 2',
  396: 'Beyond Measure',
  400: 'Livorsi Marine',
  404: 'ComNav',
  419: 'Fusion Electronics',
  421: 'Standard Horizon',
  422: 'True Heading',
  426: 'Egersund Marine Electronics As',
  427: 'Em-Trak Marine Electronics Ltd',
  431: 'Tohatsu Co Jp',
  437: 'Digital Yacht',
  438: 'Comar Systems Limited',
  440: 'Cummins',
  443: 'VDO',
  451: 'Parker Hannifin',
  459: 'Alltek Marine Electronics Corp',
  460: 'San Giorgio S.E.I.N.',
  466: 'Veethree Electronics',
  467: 'Humminbird Marine Electronics',
  470: 'SI-TEX Marine Electronics',
  471: 'Sea Cross Marine Ab',
  475: 'GME/Standard Communications',
  476: 'Humminbird Marine Electronics',
  478: 'Ocean Sat Bv',
  481: 'Chetco Digitial Instruments',
  493: 'Watcheye',
  499: 'Lcj Capteurs',
  502: 'Attwood Marine',
  503: 'Naviop S.R.L.',
  504: 'Vesper Marine',
  510: 'Marinesoft Co. LTD',
  517: 'NoLand Engineering',
  518: 'Transas USA',
  529: 'National Instruments Korea',
  532: 'Onwa Marine',
  540: 'Webasto',
  571: 'Marinecraft Co.',
  573: 'McMurdo Group',
  578: 'Advansea',
  579: 'KVH',
  580: 'San Jose Technology',
  583: 'Yacht Control',
  586: 'Suzuki Motor Corporation',
  591: 'USCG',
  595: 'ShipModul',
  600: 'Aquatic AV',
  605: 'Aventics GmbH',
  606: 'Intellian',
  612: 'SamwonIT',
  614: 'Arlt Tecnologies',
  637: 'Bavaria Yacts',
  641: 'Diverse Yacht Services',
  644: 'KUS Manufacturer',
  645: 'Garmin',
  658: 'Shenzhen Jiuzhou Himunication',
  688: 'Rockford Corporation',
  704: 'JL Audio',
  715: 'Autonnic',
  717: 'Yacht Devices',
  734: 'REAP Systems',
  735: 'Au Electronics Group',
  739: 'LxNav',
  740: 'JL Audio',
  743: 'DaeMyung Elevator',
  744: 'Woosung',
  773: 'Clarion US',
  776: 'HMI Systems',
  777: 'Ocean Signal',
  778: 'Seekeeper',
  781: 'Poly Planar',
  785: 'Fischer Panda DE',
  795: 'Broyda Industries',
  796: 'Canadian Automotive',
  797: 'Tides Marine',
  798: 'Lumishore',
  799: 'Still Water Designs and Audto',
  802: 'SPBI SA Ets BJTechnologie',
  803: 'Gill Sensors',
  811: 'Blue Water Desalination',
  815: 'Flir Systems',
  824: 'Undheim Systems',
  838: 'TeamSurv',
  844: 'Fell Marine',
  847: 'Oceanvolt',
  862: 'Prospec',
  868: 'Data Panel Corp',
  890: 'L3 Technologies Maritime Systems',
  894: 'Rhodan Marine Systems',
  896: 'Nexfour Solutions',
  905: 'ASA Electronics',
  909: 'Marines Co (South Korea)',
  911: 'Nautic-On, A Brunswick Company',
  930: 'Ecotronix Corp',
  944: 'Zonisa Marine',
  951: 'Exor International S.p.A.',
  962: 'Timbolier Industries',
  968: 'Cox Powertrain',
  969: 'Blue Sea',
  981: 'Kobelt',
  1008: 'Lintest SmartBoat',
  1011: 'Soundmax',
  1020: 'Onyx Marine Automation s.r.l',
  1021: 'Entratech',
  1022: 'ITC Inc.',
  1023: 'PEAK-System Technik GmbH',
  1029: 'The Marine Guardian LLC',
  1034: 'Siren Marine',
  1047: 'Sonic Corporation',
  1051: 'ProNav',
  1053: 'Stillwater Designs / Kicker',
  1059: 'Boatrax',
  1062: 'ComNav',
  1065: 'CALYPSO Instruments',
  1066: 'Spot Zero Water',
  1070: 'Quick-teck Electronics Ltd',
  1075: 'Uniden America',
  1083: 'Nauticoncept',
  1084: 'Shadow-Caster LED lighting LLC',
  1088: 'E-T-A Circuit Breakers',
  1092: 'Scheiber',
  1095: 'Wetsounds',
  1140: 'Across Ocean Systems Ltd.',
  1305: 'Dragonfly Energy',
  1439: 'PredictWind',
  1850: 'Teleflex',
  1851: 'Raymarine',
  1852: 'Navionics',
  1853: 'Japan Radio Co',
  1854: 'Northstar Technologies',
  1855: 'Furuno',
  1856: 'Trimble',
  1857: 'Simrad - Navico',
  1858: 'Litton',
  1859: 'Kvasar Ab',
  1860: 'Mmp',
  1861: 'Vector Cantech',
  1862: 'Sanshin Industries/Yamaha Marine',
  1863: 'Faria Instruments',  
};

export const DEVICE_CLASSES: Record<number, string> = {
  0: 'Reserved for 2000 Use',
  10: 'System tools',
  20: 'Safety systems',
  25: 'Internetwork device',
  30: 'Electrical Distribution',
  35: 'Electrical Generation',
  40: 'Steering and Control surfaces',
  50: 'Propulsion',
  60: 'Navigation',
  70: 'Communication',
  75: 'Sensor Communication Interface',
  80: 'Instrumentation/general systems',
  85: 'External Environment',
  90: 'Internal Environment',
  100: 'Deck + cargo + fishing equipment systems',
  110: 'Human Interface',
  120: 'Display',
  125: 'Entertainment',
};

export const DEVICE_FUNCTIONS: Record<number, Record<number, string>> = {
  // Class 10: System tools
  10: {  
    130: 'Diagnostic',
    140: 'Bus Traffic Logger',
  },
  20: {    
    110: 'Alarm Enunciator',
    130: 'Emergency Position Indicating Radio Beacon (EPIRB)',
    135: 'Man Overboard',
    140: 'Voyage Data Recorder',
    150: 'Camera',
  },
  25: {    
    130: 'PC Gateway',
    131: 'NMEA 2000 to Analog Gateway',
    132: 'Analog to NMEA 2000 Gateway',
    133: 'NMEA 2000 to Serial Gateway',
    135: 'NMEA 0183 Gateway',
    136: 'NMEA Network Gateway',
    137: 'NMEA 2000 Wireless Gateway',
    140: 'Router',
    150: 'Bridge',
    160: 'Repeater',
  },
  30: {    
    130: 'Binary Event Monitor',
    140: 'Load Controller',
    141: 'AC/DC Input',
    150: 'Function Controller',
  },
  35: {    
    140: 'Engine',
    141: 'DC Generator/Alternator',
    142: 'Solar Panel (Solar Array)',
    143: 'Wind Generator (DC)',
    144: 'Fuel Cell',
    145: 'Network Power Supply',
    151: 'AC Generator',
    152: 'AC Bus',
    153: 'AC Mains (Utility/Shore)',
    154: 'AC Output',
    160: 'Power Converter - Battery Charger',
    161: 'Power Converter - Battery Charger+Inverter',
    162: 'Power Converter - Inverter',
    163: 'Power Converter - DC',
    170: 'Battery',
    180: 'Engine Gateway',
  },
  40: {    
    130: 'Follow-up Controller',
    140: 'Mode Controller',
    150: 'Autopilot',
    155: 'Rudder',
    160: 'Heading Sensors',
    170: 'Trim (Tabs)/Interceptors',
    180: 'Attitude (Pitch, Roll, Yaw) Control',
  },
  50: {    
    130: 'Engineroom Monitoring',
    140: 'Engine',
    141: 'DC Generator/Alternator',
    150: 'Engine Controller',
    151: 'AC Generator',
    155: 'Motor',
    160: 'Engine Gateway',
    165: 'Transmission',
    170: 'Throttle/Shift Control',
    180: 'Actuator',
    190: 'Gauge Interface',
    200: 'Gauge Large',
    210: 'Gauge Small',
  },
  60: {    
    130: 'Bottom Depth',
    135: 'Bottom Depth/Speed',
    136: 'Bottom Depth/Speed/Temperature',
    140: 'Ownship Attitude',
    145: 'Ownship Position (GNSS)',
    150: 'Ownship Position (Loran C)',
    155: 'Speed',
    160: 'Turn Rate Indicator',
    170: 'Integrated Navigation',
    175: 'Integrated Navigation System',
    190: 'Navigation Management',
    195: 'Automatic Identification System (AIS)',
    200: 'Radar',
    201: 'Infrared Imaging',
    205: 'ECDIS',
    210: 'ECS',
    220: 'Direction Finder',
    230: 'Voyage Status',
  },
  70: {    
    130: 'EPIRB',
    140: 'AIS',
    150: 'DSC',
    160: 'Data Receiver/Transceiver',
    170: 'Satellite',
    180: 'Radio-telephone (MF/HF)',
    190: 'Radiotelephone',
  },
  75: {    
    130: 'Temperature',
    140: 'Pressure',
    150: 'Fluid Level',
    160: 'Flow',
    170: 'Humidity',
  },
  80: {    
    130: 'Time/Date Systems',
    140: 'VDR',
    150: 'Integrated Instrumentation',
    160: 'General Purpose Displays',
    170: 'General Sensor Box',
    180: 'Weather Instruments',
    190: 'Transducer/General',
    200: 'NMEA 0183 Converter',
  },
  85: {    
    130: 'Atmospheric',
    160: 'Aquatic',
  },
  90: {    
    130: 'HVAC',
  },
  100: {   
    130: 'Scale (Catch)',
  },
  110: {   
    130: 'Button Interface',
    135: 'Switch Interface',
    140: 'Analog Interface',
  },
  120: {   
    130: 'Display',
    140: 'Alarm Enunciator',
  },
  125: {   
    130: 'Multimedia Player',
    140: 'Multimedia Controller',
  },
};

export const INDUSTRY_GROUPS: Record<number, string> = {
  0: 'Global',
  1: 'Highway',
  2: 'Agriculture',
  3: 'Construction',
  4: 'Marine',
  5: 'Industrial',
};

export const PGN_DESCRIPTIONS: Record<number, { name: string; category: string; isHealthRelated?: boolean }> = {
  59392: { name: 'ISO Acknowledgment', category: 'Management', isHealthRelated: true },
  59904: { name: 'ISO Request', category: 'Management', isHealthRelated: true },
  60160: { name: 'ISO Transport Protocol, Data Transfer', category: 'Management', isHealthRelated: true },
  60416: { name: 'ISO Transport Protocol, Connection Management', category: 'Management', isHealthRelated: true },
  60928: { name: 'ISO Address Claim', category: 'Management', isHealthRelated: true },
  126208: { name: 'NMEA Request / Command / Acknowledge', category: 'Management', isHealthRelated: true },
  126464: { name: 'PGN List (TX / RX)', category: 'Management', isHealthRelated: true },
  126992: { name: 'System Time', category: 'System' },
  126993: { name: 'Heartbeat', category: 'Management', isHealthRelated: true },
  126996: { name: 'Product Information', category: 'Management', isHealthRelated: true },
  126998: { name: 'Configuration Information', category: 'Management', isHealthRelated: true },
  127237: { name: 'Heading/Track Control', category: 'Steering' },
  127245: { name: 'Rudder', category: 'Steering' },
  127250: { name: 'Vessel Heading', category: 'Navigation' },
  127251: { name: 'Rate of Turn', category: 'Navigation' },
  127257: { name: 'Attitude (Pitch/Roll/Yaw)', category: 'Navigation' },
  127258: { name: 'Magnetic Variation', category: 'Navigation' },
  127488: { name: 'Engine Parameters, Rapid Update', category: 'Engine' },
  127489: { name: 'Engine Parameters, Dynamic', category: 'Engine' },
  127493: { name: 'Transmission Parameters, Dynamic', category: 'Engine' },
  127505: { name: 'Fluid Level', category: 'Electrical/Engine' },
  127506: { name: 'DC Detailed Battery Status', category: 'Electrical' },
  127508: { name: 'Battery Status', category: 'Electrical' },
  128259: { name: 'Speed, Water Referenced', category: 'Navigation' },
  128267: { name: 'Water Depth', category: 'Navigation' },
  128275: { name: 'Distance Log', category: 'Navigation' },
  129025: { name: 'Position, Rapid Update', category: 'Navigation' },
  129026: { name: 'COG & SOG, Rapid Update', category: 'Navigation' },
  129029: { name: 'GNSS Position Data', category: 'Navigation' },
  129038: { name: 'AIS Class A Position Report', category: 'AIS' },
  129039: { name: 'AIS Class B Position Report', category: 'AIS' },
  129044: { name: 'Datum', category: 'Navigation' },
  129283: { name: 'Cross Track Error', category: 'Navigation' },
  129284: { name: 'Navigation Data', category: 'Navigation' },
  129285: { name: 'Navigation - Route/WP Information', category: 'Navigation' },
  129539: { name: 'GNSS DOPs', category: 'Navigation' },
  129540: { name: 'GNSS Sats in View', category: 'Navigation' },
  130306: { name: 'Wind Data', category: 'Environmental' },
  130310: { name: 'Environmental Parameters', category: 'Environmental' },
  130311: { name: 'Environmental Parameters (Deprecated)', category: 'Environmental' },
  130312: { name: 'Temperature', category: 'Environmental' },
  130314: { name: 'Actual Pressure', category: 'Environmental' },
  130316: { name: 'Temperature, Extended Range', category: 'Environmental' },
  130577: { name: 'Direction Data', category: 'Navigation' },
};

export const CONTROLLER_STATE: Record<number, string> = {
  0: 'Error Active',
  1: 'Error Passive',
  2: 'Bus Off',
  3: '-',
};


export const EQUIPMENT_STATUS: Record<number, string> = {
  0: 'Operational',
  1: 'Fault',
  2: '-',
  3: '-',
};

export function getManufacturerName(code: number): string {
  return MANUFACTURERS[code] || `Manufacturer #${code}`;
}

export function getDeviceClassName(code: number): string {
  return DEVICE_CLASSES[code] || `Class #${code}`;
}

export function getDeviceFunctionName(classCode: number, funcCode: number): string {
  if (DEVICE_FUNCTIONS[classCode] && DEVICE_FUNCTIONS[classCode][funcCode]) {
    return DEVICE_FUNCTIONS[classCode][funcCode];
  }
  return `Function #${funcCode}`;
}

export function getControllerState(code: number): string {
  return CONTROLLER_STATE[code] || `Controller State #${code}`;
}

export function getEquipmentStatus(code: number): string {
  return EQUIPMENT_STATUS[code] || `Equipment Status #${code}`;
}


export function getIndustryGroupName(code: number): string {
  return INDUSTRY_GROUPS[code] || `Group #${code}`;
}

export function getPgnDescription(pgn: number): { name: string; category: string; isHealthRelated: boolean } {
  if (PGN_DESCRIPTIONS[pgn]) {
    const item = PGN_DESCRIPTIONS[pgn];
    return {
      name: item.name,
      category: item.category,
      isHealthRelated: !!item.isHealthRelated,
    };
  }
  return {
    name: `PGN ${pgn}`,
    category: pgn < 65536 ? 'ISO / Single' : 'NMEA 2000 Data',
    isHealthRelated: pgn < 65536 || pgn === 126464 || pgn === 126993 || pgn === 126996,
  };
}
